DROP DATABASE IF EXISTS players;
DROP DATABASE IF EXISTS players_db;
CREATE DATABASE IF NOT EXISTS players_db;

USE players_db;

CREATE TABLE players (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
race INT UNSIGNED,
PRIMARY KEY(id),
FOREIGN KEY (race) REFERENCES race(id)
)

CREATE TABLE races (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
type VARCHAR(10) NOT NULL,
faction_id INT UNSIGNED NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (faction_id) REFERENCES faction(id)
)

